# Generated by Django 3.2.7 on 2021-11-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='image_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='image_name',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='image_title',
            new_name='title',
        ),
    ]
